### ISSUE TITLE
Support .NET 7.0

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#10846]
Tracking epic for all our net7.0-related issues

- [ ] https://github.com/nuget/home/issues/10872
- [ ] https://github.com/NuGet/Home/issues/10430
- [ ] https://github.com/nuget/home/issues/6279
- [ ] https://github.com/nuget/home/issues/7815
- [ ] https://github.com/nuget/home/issues/9667
- [x] https://github.com/nuget/home/issues/9347
- [x] https://github.com/nuget/home/issues/5154
- [x] https://github.com/nuget/home/issues/5926
