### ISSUE TITLE
[Epic]: NuGet-based MSBuild project SDK resolver improvements

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#11441]
Since its original development, the NuGet-based MSBuild project SDK resolver has needed some improvements.  Several fixes have been shipped over the years but there are still some issues that we should fix.  Other general improvements are also needed.

# Open Issues ([Query](https://github.com/NuGet/Home/issues?q=is%3Aopen+is%3Aissue+label%3AProduct%3AMSBuildSDKResolver+label%3AType%3ABug))
- [x] https://github.com/dotnet/msbuild/issues/7453
- [ ] https://github.com/dotnet/msbuild/issues/9164

# Fixed in 6.8
- [x] https://github.com/NuGet/NuGet.Client/pull/5409
       https://github.com/NuGet/Home/issues/11445

## Pull Requests
- [x] https://github.com/NuGet/NuGet.Client/pull/5314
       https://github.com/NuGet/Home/issues/12737
- [x] https://github.com/dotnet/msbuild/pull/7244
- [x] https://github.com/dotnet/msbuild/pull/7390
- [x] https://github.com/NuGet/NuGet.Client/pull/4367
- [x] https://github.com/NuGet/NuGet.Client/pull/4380
- [x] https://github.com/NuGet/NuGet.Client/pull/4443
- [x] https://github.com/NuGet/NuGet.Client/pull/4506
- [x] https://github.com/NuGet/NuGet.Client/pull/4507
- [x] https://github.com/dotnet/sdk/pull/24333
