### ISSUE TITLE
[Epic]: Central Package Management Improvements for 17.2

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#11504]
# Features

- [x] https://github.com/NuGet/Home/issues/11516
- [x] https://github.com/NuGet/Home/issues/10389
- [x] https://github.com/NuGet/Home/issues/11505

# Issues ([Query](https://github.com/NuGet/Home/issues?q=is%3Aopen+label%3AArea%3ARestoreCPM+-label%3AEpic+-label%3AEpic+-label%3AType%3AFeature))
- [x] https://github.com/NuGet/Home/issues/10327
- [x] https://github.com/NuGet/Home/issues/10074
- [x] https://github.com/NuGet/Home/issues/11696

# Pull Requests

- [x] https://github.com/NuGet/NuGet.Client/pull/4426
- [x] https://github.com/NuGet/NuGet.Client/pull/4025
- [x] https://github.com/dotnet/project-system/pull/7985
- [x] https://github.com/NuGet/NuGet.Client/pull/4505
- [x] https://github.com/NuGet/docs.microsoft.com-nuget/pull/2692
- [x] https://github.com/dotnet/project-system/pull/8028
- [x] https://github.com/NuGet/NuGet.Client/pull/4523
- [x] https://github.com/NuGet/NuGet.Client/pull/4533

# Documentation
- [x] https://github.com/NuGet/docs.microsoft.com-nuget/issues/2674

**Comment by jeffkl** [comment]
These improvements are available in Visual Studio 2022 17.2 Preview 4 or above
