### ISSUE TITLE
[Feature]: add dotnet nuget why to dotnet CLI

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11943]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

This is a tracking issue for feature request https://github.com/NuGet/Home/issues/11782

Design spec - [dotnet nuget why command](https://github.com/NuGet/Home/blob/dev/accepted/2022/dotnet-nuget-why-proposal.md) ([Spec PR](https://github.com/NuGet/Home/pull/11875))

Proof of concept: https://github.com/NuGet/NuGet.Client/tree/pragnya17-dotnet-nuget-why ([compare](https://github.com/NuGet/NuGet.Client/compare/dev...pragnya17-dotnet-nuget-why))

### Additional Context and Details

- [x] Add `dotnet nuget why` command - https://github.com/NuGet/Client.Engineering/issues/2862
- [x] Add docs to `dotnet/docs` - https://github.com/NuGet/Home/issues/13499
- [x] Add integration to `dotnet/sdk` - https://github.com/NuGet/Client.Engineering/issues/2861

**Comment by kartheekp-ms** [comment]
proof of concept at: https://github.com/NuGet/NuGet.Client/tree/pragnya17-dotnet-nuget-why
