### ISSUE TITLE
[Epic]: Add support for central package management to Visual Studio Package Manager UI

### ISSUE THREAD

**Issue by martinrrm** [NuGet/Home#12231]
This is a tracking epic for work related to adding support for CPM in PM UI

- [ ] https://github.com/NuGet/Home/issues/11826
- [x] https://github.com/NuGet/Home/issues/12229
- [x] https://github.com/NuGet/Home/issues/12230

**Comment by nkolev92** [comment]
All child issues are closed here: https://github.com/NuGet/Home/issues/9015.
