### ISSUE TITLE
Add a dotnet nuget config command

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#12296]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

Add a dotnet nuget config command to manage NuGet configuration settings.

Tracking issues:
- [x] Spec: https://github.com/NuGet/Home/issues/12297
- [x] Implement dotnet nuget config path(seasons of giving): https://github.com/NuGet/Home/issues/8420
- [ ] NuGet config command doesn't check if the key is valid: https://github.com/NuGet/Home/issues/12345
- [ ] Implement dotnet nuget config get
- [ ] Implement dotnet nuget config set/unset

**Comment by heng-liu** [comment]
Close this as a duplicate of https://github.com/NuGet/Home/issues/12469
