### ISSUE TITLE
[Epic]: Central Package Management improvements for 17.5

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#12301]
## Issues
- [x] https://github.com/NuGet/Home/issues/12278
- [x] https://github.com/NuGet/Home/issues/12276

## Pull Requests
- [x] https://github.com/NuGet/NuGet.Client/pull/4958
- [x] https://github.com/NuGet/NuGet.Client/pull/4952

**Comment by slang25** [comment]
@jeffkl is this PR / branch being tracked anywhere:
https://github.com/NuGet/NuGet.Client/pull/4700
For many at my company this one is a show-stopper for CPM adoption.

**Comment by slang25** [comment]
Should this be added to the list?
https://github.com/NuGet/NuGet.Client/pull/4832

**Comment by jeffkl** [comment]
@slang25 tooling support for central package management is tracked here: https://github.com/NuGet/Home/issues/9015

@martinrrm  will `dotnet add package` support ship in .NET SDK 7.0.100 or 7.0.200?

**Comment by slang25** [comment]
https://github.com/NuGet/Home/issues/9015#issuecomment-1442083500
