### ISSUE TITLE
[Epic]: Central Package Management improvements for 17.6

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#12413]
# Committed Issues
- [x] https://github.com/NuGet/Home/issues/12270
       https://github.com/NuGet/NuGet.Client/pull/4953
- [x] https://github.com/NuGet/Home/issues/12368
       https://github.com/NuGet/NuGet.Client/pull/5064
- [x] https://github.com/NuGet/Home/issues/12285
       https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CPS/pullrequest/453924
- [x] https://github.com/NuGet/Home/issues/12359
- [x] https://github.com/NuGet/Home/issues/12269
       https://github.com/NuGet/NuGet.Client/pull/4954
- [x] https://github.com/NuGet/Home/issues/12500
       https://github.com/NuGet/NuGet.Client/pull/5103

**Comment by jeffkl** [comment]
Release cycle for 17.6 is closed, moved unfinished issues to https://github.com/NuGet/Home/issues/12519
