### ISSUE TITLE
[Epic]: Static graph-based restore improvements

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#12414]
# Open Issues ([Query](https://github.com/NuGet/Home/issues?q=is%3Aopen+is%3Aissue+-label%3AEpic+label%3AArea%3ARestoreStaticGraph))

# Issues Fixed in Next Release
- [x] https://github.com/NuGet/NuGet.Client/pull/5573
       https://github.com/NuGet/Home/issues/13140

# Issues fixed in 17.9
- [x] https://github.com/NuGet/Home/issues/9300
       https://github.com/NuGet/NuGet.Client/pull/5512

# Issues fixed in 17.8
- [x] https://github.com/NuGet/NuGet.Client/pull/5413
       https://github.com/NuGet/Home/issues/11968
- [x] https://github.com/NuGet/NuGet.Client/pull/5453
       https://github.com/NuGet/Home/issues/12907

# Issues fixed in 17.6
- [x] https://github.com/NuGet/Home/issues/12374
       https://github.com/NuGet/NuGet.Client/pull/5042
- [x] https://github.com/NuGet/Home/issues/12322
       https://github.com/NuGet/NuGet.Client/pull/5068
- [x] https://github.com/dotnet/msbuild/issues/8523
       https://github.com/dotnet/msbuild/pull/8533
- [x] https://github.com/NuGet/Home/issues/12372
       https://github.com/NuGet/NuGet.Client/pull/5085
