### ISSUE TITLE
[Epic]: NuGet configuration CLI for dotnet.exe

### ISSUE THREAD

**Issue by martinrrm** [NuGet/Home#12469]
Feature work for https://github.com/NuGet/Home/blob/dev/proposed/2022/dotnet-nuget-config-spec.md
- [x] https://github.com/NuGet/Home/issues/8420
- [x] https://github.com/NuGet/Home/issues/12475
- [x] https://github.com/NuGet/Home/issues/12476
- [x] https://github.com/NuGet/Home/issues/12477

**Comment by dainizzz** [comment]
- [ ] https://github.com/NuGet/Home/issues/8420
- [ ] https://github.com/NuGet/Home/issues/12475
- [ ] https://github.com/NuGet/Home/issues/12476
- [ ] https://github.com/NuGet/Home/issues/12477

**Comment by dainizzz** [comment]
Blocked until migration work is completed: https://github.com/NuGet/Home/issues/12686

**Comment by nkolev92** [comment]
@martinrrm 
What's left here?

Do we have the dotnet.exe parsing code done yet?
Is it that + merging the feature branch? https://github.com/NuGet/NuGet.Client/pull/5158

**Comment by martinrrm** [comment]
@nkolev92 Closing it, the work for this is done, I'm still working in migrating the commands to use a new package, Arturo wanted to not merge this into dev until we finish the migration which will take a few more weeks to finish.

**Comment by martinrrm** [comment]
Migration work is being tracked in https://github.com/NuGet/Home/issues/12686

**Comment by martinrrm** [comment]
Reopening to keep track of this until gets merged into the main branch

**Comment by martinrrm** [comment]
Closing, this is already in main 🥳

**Comment by nkolev92** [comment]
Should be available in 8.0.2xx/6.9 equivalent, but we missed announcing it.
