### ISSUE TITLE
[Epic] Support SBOMs for NuGet packages

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#12497]
A [SBOM](https://www.cisa.gov/sbom) is a nested inventory; a list of ingredients that make up software components.

This epic tracks the work to support providing a [SPDX formatted](https://spdx.github.io/spdx-spec/v2.2.2/introduction/) and [NTIA compliant](https://www.ntia.gov/files/ntia/publications/sbom_minimum_elements_report.pdf) SBOM inside of a NuGet package based on the [SBOM Everywhere](https://github.com/ossf/sbom-everywhere/blob/main/reference/mobilization_plan.pdf) initiative to bring a seamless interoperability end-to-end for security use cases at five major levels of software development:

1. Clients and SDKs
2. Package management plugins
3. Native package manager integration
4. Containerization integration
5. Application/solution integration/deployment

We will most likely utilize [sbom-tool](https://github.com/microsoft/sbom-tool) to accomplish this task.

- [x] https://github.com/microsoft/sbom-tool/pull/674
- [ ] https://github.com/NuGet/Home/issues/13142
- [ ] https://github.com/NuGet/Home/issues/13690
- [ ] https://github.com/NuGet/Home/issues/13755
- [ ] https://github.com/microsoft/sbom-tool/issues/693

Please 👍 or 👎 this comment to help us with the direction of this epic & leave as much feedback/questions/concerns as you'd like on this issue itself and we will get back to you shortly.

Further tracking issues will be created shortly as requirements are gathered and planned.

**Comment by TiberiusDRAIG** [comment]
Is the intention to support only the SPDX format or is there scope for supporting others like CycloneDX?

**Comment by JonDouglas** [comment]
@TiberiusDRAIG The intention would be to support what sbom-tool supports at this point.

**Comment by Malcolmnixon** [comment]
With this being removed from the 6.8 milestone:
- Is there a new planned delivery for this?
- Is there any information on where the SBOMs would/should be located in NuGet packages so we can manually construct compliant packages using sbom-tool today?

**Comment by JonDouglas** [comment]
Don't read into our backlog tagging too much. It just means that we finished our 6.8 release recently.

**Comment by JonDouglas** [comment]
Just so people know, you can go try out the initial SBOM package by following this issue here:

https://github.com/microsoft/sbom-tool/pull/674

**Comment by dotMorten** [comment]
@JonDouglas This looks cool. I have a native library inside my nuget package, and I do have an sbom for that native library. Is there a way to get that merged in as well?

**Comment by SimonCropp** [comment]
given Microsoft.Sbom.Targets has been available for a while now, should this be closed?

**Comment by dlemstra** [comment]
> given Microsoft.Sbom.Targets has been available for a while now, should this be closed?

It would still be nice if an SBOM for native dependencies that are part of the NuGet package can also be included in the package?
