### ISSUE TITLE
Opt-out of "HTTPs everywhere" by setting allowInsecureConnections to true

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#12785]
When a non-HTTPS source is used, there will be an warning/error ([blog](https://devblogs.microsoft.com/nuget/https-everywhere/)).  
We need to provide a way to opt-out of this behavior, by setting allowInsecureConnections to true in NuGet.Config.
Spec: https://github.com/NuGet/Home/blob/dev/proposed/2023/InsecureConnectionsDisableCertificateValidation.md

- [x] [add an allowInsecureConnections property in NuGet.Config](https://github.com/NuGet/Home/issues/12786)
- [x] [do not warn for HTTP sources in PackageReference restore scenarios in all NuGet tools](https://github.com/NuGet/Home/issues/12787)
- [x] [do not warn for HTTP sources in packages.config restore scenarios](https://github.com/NuGet/Home/issues/12788)
- [x] [do not warn for HTTP sources when http sources are used in push/delete operations](https://github.com/NuGet/Home/issues/12789)
- [x] [do not warn for HTTP sources when http sources are used in search/list package](https://github.com/NuGet/Home/issues/12790)
- [x] [do not warn for HTTP sources when http sources are used in source command](https://github.com/NuGet/Home/issues/12791)
- [x] [Do not show warning icons to HTTP sources in VS Options NuGet Package Manager when allowInsecureConnections is true](https://github.com/NuGet/Home/issues/12792)
- [x] [Opt-out of "HTTPS everywhere" for other scenarios](https://github.com/NuGet/Home/issues/12793)

**Comment by ZenithElevate** [comment]
So, what happened to this?
Where did this go?

allowInsecureConnections="true" still is not working for push operations.

Self-signed certificates are not accepted, not even after adding them and CA to the machine cert store.
We are essentially prevented from pushing nuget packages to our own nuget servers, unless we endure the trouble of obtaining trusted 3d party SSL certs. Oh, well, on a 2nd thought, I have no idea whether obtaining a trusted cert **is** a solution because I have yet to see that work.

This is not reasonable.
