### ISSUE TITLE
[Epic]Deprecate http usage: Promote from warning to error

### ISSUE THREAD

**Issue by Nigusu-Allehu** [NuGet/Home#13289]
### NuGet Product(s) Affected

NuGet.exe, MSBuild.exe, dotnet.exe

### Current Behavior

We have [NU1803](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1803) warnings across NuGet. Promote from warning to error.

- [x] [Promote from warning to error in restore scenarios](https://github.com/NuGet/Home/issues/13353)
- [x] [Promote from warning to error in push operations](https://github.com/NuGet/Home/issues/13342)
- [x] [Promote from warning to error in delete operations](https://github.com/NuGet/Home/issues/13341)
- [x] [Promote from warning to error in search package](https://github.com/NuGet/Home/issues/13316)
- [x] [Promote from warning to error in list package](https://github.com/NuGet/Home/issues/13323)
- [x] [Promote from warning to error in source command](https://github.com/NuGet/Home/issues/13333)
- [x] [Promote from warning to error in VS Options NuGet Package Manager](https://github.com/NuGet/Home/issues/13354)
- [ ] [Show an error when a non https source is used in a resource in a service index](https://github.com/NuGet/Home/issues/13364)
- [x] [Add `--allow-insecure-connections` option to dotnet.exe](https://github.com/NuGet/Home/issues/13396)

**Comment by nkolev92** [comment]
Remember to add the scenarios where the service index is https, but through the index.json the links for certain resources in there are http. 

That was something that was on purpose left out during the warn stage as the effort was too much.

**Comment by nkolev92** [comment]
reopening since we're slightly delaying the merge.
