### ISSUE TITLE
[EPIC] Build Provenance for NuGet

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#13581]
- [x] [Support OIDC authentication](https://github.com/NuGet/NuGetGallery/issues/9332)
    - [ ] Integrate with CI/CD systems to request OIDC tokens (GitHub Actions / Azure DevOps)
    - [ ] Trading of ID token from OIDC Service <img width="177" alt="image" src="https://github.com/NuGet/Home/assets/1288848/85b69267-fd3a-4b79-8080-4a2e4d36a6ed">
- [ ] Collect build information from CI/CD system so I can generate build provenance for my package
    - [ ] Extend CLI/push to collect and send additional build information (investigate transactional nature of symbols compared to this build information)
    - [ ] Decide of bundle format of attestation using in-toto/SLSA standards
    - [ ] Consider implementation of signing functionality using existing infrastructure or Fulcio?
- [ ] Extend the NuGet.org registry to support build provenance so it can store and verify the provenance information
    - [ ] Ability to accept and store build provenance data
    - [ ] Verify incoming provenance bundles are "good"
    - [ ] Generate and publish attestation documents
- [ ] Verify the provenance bundle so I trust the integrity / origin of the package (TODO)
- [ ] Provide provenance information to users
    - [ ] The NuGet.org web UI displays provenance information
    - [ ] The NuGet.org API will expose the provenance data
    - [ ] The dotnet/NuGet CLI/Visual Studio/etc can retrieve and verify provenance for packages

Prior Art

- https://github.com/npm/cli/blob/latest/workspaces/libnpmpublish/lib/publish.js#L173

User Stories

1. We collect build information from supported CI/CD
2. We assemble the build information in a standard format
3. We send this build information to NuGet registry
4. We accept and store the build provenance data in NuGet.org
5. We verify incoming provenance bundles
6. We generate and publish attestation documents
7. <Verify User Stories>
8. We can view the provenance information on the registry web UI
9. We can retrieve provenance information via the registry API
10. The tooling provides a way to retrieve and verify provenance information

**Comment by mu88** [comment]
Is there any news about this feature? Any plans to implement it in the near future?
