### ISSUE TITLE
Show Owner information in Package Manager UI

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#13582]
## Before 17.10
- [ ] ~https://github.com/NuGet/NuGet.Client/pull/5505~
- [x] https://github.com/NuGet/Home/pull/13030

## 17.10 🚀
- [x] https://github.com/NuGet/Home/issues/13186
- [x] https://github.com/NuGet/docs.microsoft.com-nuget/pull/3280

## 17.11 🚀
- [x] https://github.com/NuGet/Home/issues/12501
  - [x] https://github.com/NuGet/NuGet.Client/pull/5766
- [x] https://github.com/NuGet/NuGet.Client/pull/5763
- [x] https://github.com/NuGet/NuGet.Client/pull/5843
  - [x] https://github.com/NuGet/Home/pull/13514

### P1
- [x] https://github.com/NuGet/Client.Engineering/issues/2916 (formerly https://github.com/NuGet/docs.microsoft.com-nuget/issues/3287)

### P2
- [x]  https://github.com/NuGet/Home/issues/10666
  - [x] https://github.com/NuGet/Home/issues/13686
- [ ] https://github.com/NuGet/Home/issues/14005 

### P3
- [ ] https://github.com/NuGet/Home/issues/13516
  - [ ] (🚧 WIP) https://github.com/NuGet/Home/pull/13530
