### ISSUE TITLE
Show vulnerability data for solution-level transitive packages

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#13697]
Make transitive packages in Solution PM UI query the vulnerability service to see if it is vulnerable and display the vulnerability indicator in the packages list.
Work needed
- [x] https://github.com/NuGet/Home/issues/13758
- [x] https://github.com/NuGet/Home/issues/13759
- [x] https://github.com/NuGet/Home/issues/13760
- [x] https://github.com/NuGet/Home/issues/13761
- [x] https://github.com/NuGet/Home/issues/13762
