### ISSUE TITLE
[Epic] NuGet OIDC (a.k.a. "Trusted Publishers")

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#13731]
### NuGet Product(s) Involved

NuGet SDK, Other/NA

### The Elevator Pitch

"Trusted Publishers" is a term for using OIDC standard to exchange short-lived identity tokens between a trusted third-party service and NuGet.org. This method can be used in automated environments and eliminates the need to use manually generated API tokens to authenticate with NuGet when publishing.

A package author should be able to get a provisioned short-lived API token through OIDC token exchange to prevent the need for any long-lived API keys. This will bring “trusted publishers” to NuGet.org.

### Additional Context and Details

- [ ] https://github.com/NuGet/NuGetGallery/issues/9332 (Dependent on this)
    - [ ] #13673 
- [x] AzDo support (one-pager)
- [ ] OpenSSF Rational (half/one-pager)
- [x] MVP Feedback
- [ ] Client Short-lived API Key Refresh Model/Considerations (How long for say a .NET release?)
- [ ] Potential threat model for longer-lived API keys & ADO integration
    - [ ] Is 15-minute long enough for larger releases?
- [ ] GitHub Action "action" and AzDo Pipeline Task for "Trusted Publisher"
- [ ] NuGet.org Affordance for "Trusted Publisher"
- [ ] Blog & Documentation

**Comment by Drake53** [comment]
Is this compatible with github releases? I updated my workflow as described in https://devblogs.microsoft.com/dotnet/enhanced-security-is-here-with-the-new-trust-publishing-on-nuget-org/ but now the last step fails with a 403.
Before changes: https://github.com/Drake53/War3Net/actions/runs/18057126965
After changes: https://github.com/Drake53/War3Net/actions/runs/18057065956
Commit: https://github.com/Drake53/War3Net/commit/995ed03c9f436c3a5146a4001913648910396b52
