### ISSUE TITLE
Authentication issues for Restore with multi-feeds in nuget.config

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4949]
Till now, Following issues are identified:

## Todo: 
[see Epic]

## Completed:
- [x] [Authentication] In multi-feed scenario, NuGet install does not honor the feed selected as package source in PM-UI#[5034](https://github.com/NuGet/Home/issues/5034)
- [x] NuGet should install package from local cache even if disconnected from other feeds. #[5035](https://github.com/NuGet/Home/issues/5035)
- [x] NuGet tries to repeatedly authenticate even when authentication fails or times out for one of the authentication feeds. https://github.com/NuGet/Home/issues/5373
- [x] NuGet does not remember password for custom feeds https://github.com/NuGet/Home/issues/4615

**Comment by anangaur** [comment]
Adding one more to the list:
NuGet tries to repeatedly authenticate even when authentication fails or times out for one of the authentication feeds. https://github.com/NuGet/Home/issues/5373

**Comment by dtivel** [comment]
Also https://github.com/NuGet/Home/issues/4615

**Comment by anangaur** [comment]
Another one https://github.com/NuGet/Home/issues/5607

**Comment by nkolev92** [comment]
Related and dups of some of these as well. 
https://github.com/NuGet/Home/issues/5848

**Comment by donnie-msft** [comment]
All issues in this epic are closed.
