### ISSUE TITLE
Justin - Bug jail

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5570]
Clean up remaining issues for 4.3

- [x] #5583 Dotnet restore hangs indefinitely   (globs?)
- [x] #5530 4.3.0-preview3 expects certain targets to exist (nuget.exe regression, msbuild /t:restore was broken) - merged into dev.

Shepharding CLI Fix, with problem in VS  - may take a fix from us afterall ... need to drive.
- [x] #5529 RestoreAdditionalProjectSources nominations for multi TFM projects are different
