### ISSUE TITLE
Fix 4.4 bugs

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5688]
Targeting following bug fixes: 

 - [x] https://github.com/NuGet/Home/issues/5655 Invalid warning "Assembly outside lib folder." in dotnet pack
 - [x] https://github.com/NuGet/Home/issues/4719 `dotnet pack --include-source` places code sub-directories in the root of the package.
 - [x] https://github.com/NuGet/Home/issues/5502 Pack metadata doesn't work if project is multi-targeted
 - [ ] https://github.com/NuGet/Home/issues/5016 NuGet.exe pack performance problem with `..` relative path
 - [x] https://github.com/NuGet/Home/issues/5700 PackagePathResolver.GetPackageDirectoryName should be virtual
 - [ ] https://github.com/NuGet/Home/issues/5706 The performance of "nuget pack" decreases with increasing levels in the source paths
 - [x] https://github.com/NuGet/Home/issues/5676 Enabling GeneratePackageOnBuild deleted my entire history of packages
- [x] https://github.com/NuGet/Home/issues/5168 Enable pack to infer target framework when the property is not set (in legacy package reference based projects)
- [ ] https://github.com/NuGet/Home/issues/4587 Packing csproj with long description issues unresolvable warning about missing summary text 
- [x] https://github.com/NuGet/Home/issues/5746 NuGet.exe version log statement
- [x] https://github.com/NuGet/Home/issues/4166 Pack target can't create contentFiles with build actions correctly 
- [x] https://github.com/NuGet/Home/issues/5747 start publishing nuget.credentials as a nupkg
- [x] https://github.com/NuGet/Home/issues/5143 The msbuild pack target should have a public hook for running user targets before itself
- [x] https://github.com/NuGet/Home/issues/5374 Setting the default value of Description property doesn't work well with GenerateAssemblyInfo task
- [x] https://github.com/NuGet/Home/issues/4644 'dotnet pack' puts nuspec under obj instead of obj\Debug
- [ ] https://github.com/NuGet/Home/issues/3927 Pack should exclude items from targets/props files coming from packages
- [ ] https://github.com/NuGet/Home/issues/4142 msbuild /t:Pack always creates seperate symbols package

**Comment by rohit21agrawal** [comment]
[ ] https://github.com/NuGet/Home/issues/5655

**Comment by nkolev92** [comment]
Redundant.
