### ISSUE TITLE
4.4 bugs

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5690]
Triage and find high priority issues for 4.4

- [x] https://github.com/NuGet/Home/issues/5709 Add different msbuild task UserAgent strings for netcore vs desktop
- [x] https://github.com/NuGet/Home/issues/5630 Failed to restore packages after switch to the new project system
- [x] https://github.com/NuGet/Home/issues/4967 Read PackageReferences from CollectPackageReferences
- [x] https://github.com/NuGet/Home/issues/4582 NuGet should should burn in assets file relative to project to prevent broken projects when they are moved on disk
- [x] https://github.com/NuGet/Home/issues/4931 Filename or extension is too long
- [x] https://github.com/NuGet/Home/issues/5736 nuget.exe install TargetFramework support
- [x] https://github.com/NuGet/Home/issues/5735 Nuspec files should be read once per restore
- [x] https://github.com/NuGet/Home/issues/2405 Nuget.exe (3.+) install package with Version number and ExcludeVersion flag doesn't update package to newer version
- [x] https://github.com/NuGet/Home/issues/5737 nuget.exe install incorrectly disables caching
