### ISSUE TITLE
Fix 4.4 bugs

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#5708]
Targeting following bug fixes: 

 - [x] https://github.com/NuGet/Home/issues/5267 Nuget push fails with timeout for some packages 
 - [x] https://github.com/NuGet/Home/issues/5718 VS Running the restore command for package.config when Restore is disabled displays incorrect message 
 - [x] https://github.com/NuGet/Home/issues/5659 VS; Running the restore command when Restore is disabled displays a confusing message
 - [x] https://github.com/NuGet/Home/issues/5649 Restore will not restore mono.cecil or semver packages, but all other packages get restored.
 - [x] https://github.com/NuGet/Home/issues/5695 Source name of credential Setting in NuGet.Config are case sensitive 
- [x] https://github.com/NuGet/Home/issues/5644 Errors and Warnings - bad error when a source in unavailable.
- [x] https://github.com/NuGet/Home/issues/4648 RuntimeEnvironmentHelper.IsLinux returns true for OSX 
- [x] https://github.com/NuGet/Home/issues/5456 Init scripts are not being executed when package installed through dotnet add command [filed a bug to powershell]
- [x] https://github.com/NuGet/Home/issues/5379 Pack targets miss library layout files with UWP

**Comment by zhili1208** [comment]
Targeting following bug fixes: 

 - [ ] https://github.com/NuGet/Home/issues/5267

**Comment by nkolev92** [comment]
Redundant now.
