### ISSUE TITLE
nkolev92 4.4 7/31 - 8/18 bugs 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5721]
- [x] https://github.com/NuGet/Home/issues/5444 Cross Client no-op for legacy package reference
- [x] https://github.com/NuGet/Home/issues/5716 GetRestoreDotnetCliToolsTask fails when missing version metadata
- [x] https://github.com/NuGet/Home/issues/5419 Legacy package reference does not no-op after building on package install.
- [x] https://github.com/NuGet/Home/issues/5778 E2E tests have incompatible templates for LSL tests
