### ISSUE TITLE
Tools CLI ask summary issue

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#6200]
[Spec](https://github.com/NuGet/Home/wiki/Global-Tools---NuGet-Implementation)

- [x] Filter /tools on only TFM and RID, so the settings XML can be put in /tools folder #6197
- [x] Block package reference to tool package type when there is no property to indicate the project is a temporary project to restore the package #6198
- [x] Allow nuget.config probing start path to be able to set in project file #6199
- [x] API to get tools folder from NuGet https://github.com/NuGet/Home/issues/6260

**Comment by wli3** [comment]
Optional
- [ ] `NuGet.CommandLine.XPlat package add` support `--config`  #6210

**Comment by nkolev92** [comment]
Added the spec.

**Comment by nkolev92** [comment]
Closed in https://github.com/NuGet/NuGet.Client/pull/1900
