### ISSUE TITLE
NuGet credential plugin V2

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#6642]
[Spec](https://github.com/NuGet/Home/wiki/NuGet-cross-plat-authentication-plugin
)

Parent feature issue: https://github.com/NuGet/Home/issues/6486

- [x] Refactoring of Credential Service/Auth code to prepare for the new plugin architecture.
       
- [x] https://github.com/NuGet/Home/issues/6699 Enhance the IPC plugin protocol to add auth operation and auth message capabilities. 
Related https://github.com/NuGet/Home/wiki/NuGet-Package-Download-Plugin
Rev up the plugin protocol, add messages for credential retrieval. 
This should unblock actual credential provider work

- [x]  Discovery of plugins - https://github.com/NuGet/Home/issues/6704
- [x]  Protocol cleanup, cross-plat start-up https://github.com/NuGet/Home/issues/6706 
- [x] perf cost of startup https://github.com/NuGet/Home/issues/6744 - As of 4/9/2018
- [x] Logging contract for the auth plugin - https://github.com/NuGet/Home/issues/6762 
- [x] Credential Provider + Proxy scenario - https://github.com/NuGet/Home/issues/6923
- [x] Address cross-plat plugin *trust* validation -  https://github.com/NuGet/Home/issues/6702
The trust validation is done with Authenticode and it doesn't have a XPLAT story. 
- [x] Add caching of capaibilities for plugins - https://github.com/NuGet/Home/issues/6796 
- [x] The authenticode signature validation needs to be lazy - https://github.com/NuGet/Home/issues/6984
- [x] Understand the additional scenarios for the plugin - https://github.com/NuGet/Home/issues/6956
- [x] Add interactive flag for the restoretask and the add pkg ref commands - https://github.com/NuGet/Home/issues/7017
- [x] Documentation - https://github.com/NuGet/docs.microsoft.com-nuget/issues/909
Bugs found during development:
- [x] The serialization of GetAuthenticationCredentialRequest is incorrect - https://github.com/NuGet/Home/issues/6983
- [x] Add plugins cache clearing to the locals command - https://github.com/NuGet/Home/issues/7075
- [x] The MSBuild SDK resolver should do auth and MSBuild auth should be device flow - https://github.com/NuGet/Home/issues/7076

Post 4.8
- [x] Cleanup of Default Cred Provider - https://github.com/NuGet/Home/issues/6780

//cc
@dtivel @rrelyea

**Comment by rrelyea** [comment]
@nkolev92 - do we close this now? or push to 5.0?

**Comment by nkolev92** [comment]
I think we can close it. 

The few leftover items have their own issues already.
