### ISSUE TITLE
Signing: Enable ClientPolicies to require use of a set of Trusted Authors and Repos listed in NuGet.Config

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#6961]
This issue is to track implementation of the feature designed in https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Config-schema-changes-to-enable-trusted-signers

This is a first step feature to add support for client policies. This issue is tracking the following work:
* [x] Read and parse correctly trusted signers from nuget.config
* [x] Pass down settings from nuget.config to verification API through extraction and verify command.
* [x] Use nuget.config settings in the verification pipeline as an input and use it to verify the package.
* [x] Refactor `AllowListVerificationProvider` to receive only one allowList.
* [x] Add support for `allowUntrustedRoot` by using that flag in verify API
* [x] Forbid large package downloads when on `require` client policy.
* [x] Improve error messages - https://github.com/NuGet/Home/issues/6906

**Comment by jainaashish** [comment]
Can you link this issue to the right spec?

**Comment by PatoBeltran** [comment]
Closing this issue since the work is done and merged into 15.9 and the missing work for the CLI gesture is being tracked by https://github.com/NuGet/Home/issues/7480
