### ISSUE TITLE
Enable SHA tracking and enforcement for Packages.Config scenarios

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#7281]
We'd like to enable Packages.Config scenarios to track and enforce SHA.

For PackageReference users, project lock file will enable SHA enforcement. 
We are exploring either:
1) adding SHA as a new Attribute of the Package element in Packages.Config
2) adding lock file to Packages.Config scenarios.

@zivkan

spec: https://github.com/NuGet/Home/wiki/Packages.config-SHA-Validation

Tasks:
- [x] Create/update lock file on package install and uninstall #7951 
- [x] Update lock file on restore when lock file out-of-sync with project #8035
- [x] Validate SHA on restore #8036
- [x] Add nuget.exe command line parameters for lock file features #8038

**Comment by rrelyea** [comment]
May ship in 4.9.x, but lets track this as 5.0 for now.

**Comment by mitchdenny** [comment]
@rrelyea Are there any plans to generate lock files by default like in the NPM ecosystem?

**Comment by gilescope** [comment]
One the SHA is recorded, people can care less about where nuget actually gets the package from. If the hash matches cinders can go to the ball...
