### ISSUE TITLE
Investigate performance improvements/ perf suite / large solution restore/ no op improvements

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7940]
//cc @dtivel @rrelyea 

- [x] https://github.com/NuGet/Home/issues/8029
- [x] https://github.com/NuGet/Home/issues/7976
- [ ] https://github.com/NuGet/Home/issues/8037
- [x] https://github.com/NuGet/Home/issues/8039
- [x] https://github.com/NuGet/Home/issues/6570
- [x] https://github.com/NuGet/Home/issues/8358
- [x] https://github.com/NuGet/Home/issues/8339
- [x] https://github.com/NuGet/Home/issues/8369
- [ ] https://github.com/NuGet/Home/issues/8283

**Comment by nkolev92** [comment]
This effort can be considered complete. 
Unfinished tasks will be balanced.
