### ISSUE TITLE
Show NuGet commands in context menu

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8041]
Show `Manage NuGet Packages` as an option on
- [x] `Dependencies` node's context menu for SDK style projects https://github.com/NuGet/Home/issues/5049 (Released in 16.4 Preview 2)
- [x] `Packages` node's context menu for SDK style projects https://github.com/NuGet/Home/issues/5049 (Released in 16.4 Preview 2)
- [x] `References` node's context menu for csproj.dll based projects

(Note: 'NuGet' node was renamed to 'Packages' in 16.3)

From Developer community suggestion: https://developercommunity.visualstudio.com/content/idea/622379/add-manage-nuget-packages-to-context-menu.html
GitHub Issue: https://github.com/NuGet/Home/issues/5049

**Comment by anangaur** [comment]
Adding contents for this workitem.

Show `Manage NuGet Packages` as an option on
- [ ] `Dependencies` node's context menu for SDK style projects
- [ ] `NuGet` node's context menu for SDK style projects
- [ ] `References` node's context menu for csproj.dll based projects

- [ ] Show `Update All...` on `NuGet` node for SDK style projects
- [ ] Show `Update...` on individual NuGet packages at the top level

**Comment by anangaur** [comment]
From Developer community suggestion: https://developercommunity.visualstudio.com/content/idea/622379/add-manage-nuget-packages-to-context-menu.html

**Comment by nkolev92** [comment]
How does this relate to https://github.com/NuGet/Home/issues/7958?

Are they the same?

Can one be closed @donnie-msft or maybe this one can point to that issue?

**Comment by donnie-msft** [comment]
@nkolev92 it relates in that they both appear to be solved by the work to be done in this tracking Issue. I'll close the newest one.

**Comment by karann-msft** [comment]
From developer community suggestion:
https://developercommunity.visualstudio.com/content/idea/664078/vs-2019-managed-nuget-packages.html
> Managed Nuget Packages option should show up when right clicked on Nuget undre Dependencies as well. It shows up onlywhen right clicked on Dependencies in the soulution explorer.
