### ISSUE TITLE
4.9.x / Visual Studio 15.9.x servicing considerations

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8094]
A list of issues to be considered for servicing in 15.9.x 

Bugs: 
- [ ] https://github.com/NuGet/Home/issues/8019 - Packages Lock File - regenerate lock file when project graph changes
* Original release version: 5.1
* Other reports: 
- [ ] https://github.com/NuGet/Home/issues/7930 - Lock file not updating when package references removed
* Original release version 5.1
* Other reports: https://github.com/NuGet/Home/issues/8091
- [ ] https://github.com/NuGet/Home/issues/7889 - RestoreLockedMode - Unexpected NU1004 when ProjectReference refers to a project with custom AssemblyName.
* Original release version: 5.1
Other reports:

Features: 
- [ ] https://github.com/NuGet/Home/issues/7961 - Build Assets Transitive for VS 2017 / NuGet 4.x
* Original release version 5.0
* Other reports: Original issue, https://github.com/NuGet/Home/issues/6091.

**Comment by rrelyea** [comment]
Closing for now. Was not sufficient justification for backporting these fixes at this time.
