### ISSUE TITLE
UI delay while initializing NuGet.Configuration.ISettings type

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#8675]
Linked to ADO Bugs [959453](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959453/)

**Comment by nkolev92** [comment]
If you are gonna create these, can you please do one of the following 2:
- Link the bugs (rather than just the bug number)
- Add descriptions of the bugs.

It has a few too many levels of indirection this way :)

**Comment by kartheekp-ms** [comment]
> If you are gonna create these, can you please do one of the following 2:
> 
> * Link the bugs (rather than just the bug number)
> * Add descriptions of the bugs.
> 
> It has a few too many levels of indirection this way :)

Added hyperlinks to ADO bugs. Created separate issue #8675 to track the fix for ADO Bugs 959481.

**Comment by kartheekp-ms** [comment]
Noticed from the call stack (in debug mode) that ~500 milliseconds is spent executing MEF code. Working with VS MEF team offline.

**Comment by kartheekp-ms** [comment]
I am drafting a [spec](https://github.com/NuGet/Home/blob/dev-kartheekp-ms-uidelay8675-spec/designs/uidelay_asyncapi_IVsPackageSourceProvider.md) to create an `Async` version of [IVsPackageSourceProvider](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivspackagesourceprovider-interface) interface to move the heavyweight code in the MEF activation path out of that path and make this an async initialization so that no thread is blocked while switching to a background thread.

**Comment by kartheekp-ms** [comment]
- [x] Learn about JTF from docs and threading experts #8901 
- [ ] Spec work (review spec internally and with partners) #8902 
- [ ] Fix code and compare ETL traces to validate the fix #8903

**Comment by davkean** [comment]
@donnie-msft @nkolev92 @kartheekp-ms Can we please bump the priority of this bug? See the linked bug for details.

**Comment by davkean** [comment]
I believe this to be resolved by https://github.com/dotnet/roslyn/pull/52521.

**Comment by nkolev92** [comment]
That makes sense, given that the UI delay is caused by assembly loading on the UI thread. 

The need for an async service still exists in https://github.com/nuget/home/issues/8902, but it's not correlated to a top hitter now.
