### ISSUE TITLE
Address VS threading warnings

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8968]
Each one of these can be addressed as a separate issues. 
We should only attempt to tackle these after https://github.com/NuGet/NuGet.Client/pull/3172 has been merged.
- [x] VSTHRD003 https://github.com/NuGet/Home/issues/8976
- [x] VSTHRD010 https://github.com/NuGet/Home/issues/8978
- [x] VSTHRD100 https://github.com/NuGet/Home/issues/8975
- [x] VSTHRD109 https://github.com/NuGet/Home/issues/8978
- [x] VSSDK004 https://github.com/NuGet/Home/issues/8974
- [x] VSSDK005 https://github.com/NuGet/Home/issues/8974
- [x] VSSDK006 https://github.com/NuGet/Home/issues/8974

fyi @NuGet/nuget-client
