### ISSUE TITLE
Support .NET 6.0

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9783]
This epic contains stuff we need to do specifically to support net6.0

Spec: https://github.com/dotnet/designs/pull/174

* [x] https://github.com/nuget/home/issues/10718
* [x] https://github.com/nuget/home/issues/10819
* [x] https://github.com/nuget/home/issues/10717
* [x] https://github.com/nuget/home/issues/9913
* [x] https://github.com/nuget/home/issues/9435

**Comment by terrajobst** [comment]
@zkat, please link to the spec: https://github.com/dotnet/designs/pull/174

**Comment by zkat** [comment]
wrapping this one up.
